### ISSUE TITLE
TLS1.3's not supported

### ISSUE THREAD

**Issue by musana** [refraction-networking/utls#191]
Hello ,

I have been trying to change JA3 string using uTLS library. uTLS fails when the server support only TLS1.3 . Do you have a goal for supporting TLS1.3?

or have you any workaround for TLS1.3 issue?

![image](https://github.com/refraction-networking/utls/assets/11095899/f2599e2f-2849-4cf3-bb8d-01165b06658a)

![resim](https://github.com/refraction-networking/utls/assets/11095899/78f2bdbe-9524-46f6-a314-74e371d2d8cb)

Thanks in advance!

**Comment by gaukas** [comment]
I'm not sure if min-version as `0x0304` is a valid thing -- You might want to set the `SupportedVersions` which is backed by one of the TLS Extensions instead of setting the min version. As far as I know, uTLS uses the `min` version as the record version in the TLS record (e.g. `16 03 03` ...) and it is by RFC that this version field must not be higher than `0x0303` (TLS 1.2). That is to say, TLS 1,3 (`0x0304`) is only valid in `SupportedVersions` extension.

**Comment by gaukas** [comment]
> uTLS does not work with this ClientHello

No it does not. Because of this: 

```
        Extension: supported_versions (len=5)
            Type: supported_versions (43)
            Length: 5
            Supported Versions length: 4
            Supported Version: TLS 1.3 (0x0304)
```

Unfortunately there seems to be no clean way to fix this. When TLS 1.3 is used (`SupportedVersions` extension present), the `minVers`/`maxVers` are overwritten by the min/max found in `SupportedVersions`. 

I could try to add a dirty fix, if there's a significance for being able to do this? Could you provide a **popular** fingerprint (best to be found on https://tlsfingerprint.io/) that support ONLY TLS 1.3?

**Comment by gaukas** [comment]
Implemented a quick but perhaps dirty fix. Further evaluation needed before merge. Thanks!

**Comment by vellrya** [comment]
Thanks for your time!
This will not help in this case, because the FB server will select the 0xfb1a protocol and the following error will appear 

> tls: server selected unsupported protocol version fb1a

I think it's a fairly specialised task, and people who need to solve it can modify the library themselves)

**Comment by gaukas** [comment]
The question will be: What happens if `0xfb1a` is selected and utls does not error? 

It will be another problem, since utls cannot assume it is an alias of any known (and supported) version. 

For every `custom` protocol some degrees of customization to utls library will be inevitably required. However if #194 would help in more general use cases, we would be happy to get it merged in next tagged version.
