### ISSUE TITLE
[BUG] (Fake|Utls)PreSharedKeyExtension

### ISSUE THREAD

**Issue by VeNoMouS** [refraction-networking/utls#248]
I noticed while trying to implement / understand implementing a PSK for `UtlsPreSharedKeyExtension`  on `ClientHelloSpec`  i ran into a weird problem... so i  started looking at full raw bytes from wireshark for a full client hello replication , the PSK is not actually populated and errors out , im not sure if this due to the recent change with fakePSK to `UtlsPreSharedKeyExtension`

`empty psk detected; remove the psk extension for this connection or set OmitEmptyPsk to true to conceal it in utls`

`
1603010200010001fc0303cee3cca75d5c385f42d7389f48cf75535b403d58159fecdfdf8ef276bf97deba20a581ab3a59648aead9f3a8715e523c82bee686636cf76c50226295badba9e2ee0020aaaa130113021303c02bc02fc02cc030cca9cca8c013c014009c009d002f003501000193aaaa0000000500050100000000ff0100010000230000000b00020100000d0012001004030804040105030805050108060601001200000010000e000c02683208687474702f312e310033002b00299a9a000100001d00203fcef7f05620d78f9aee265cee94d71e0ced2e692532c18f7cdb6add0055a22d446900050003026832001b000302000200170000000a000a00089a9a001d00170018002d0002010100000010000e00000b746c732e706565742e7773002b000706fafa03040303caca0001000015002c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000029009c00770071854aabbb2c615e18010431cde6cd36b8e5184aab74d3f8e663befea450d68633ad4fbdf8d14a1e2790e04a3434806eea98e7a33fe5c2c5e74c44dba77c7b1da3e475b9fd6345eb5ad557002f95f36f771a40736de379b4cfe741d351d4121963f35abbd4b4c1a2c1c25e234ab30cb2b786857cf5e6002120ff98ad8e80d2b6d6d2f3e3ab73a5447afe9b79cb9e143aaac613b671b1910d58
`

This occurs if `RealPSKResumption` is true or false

**Comment by VeNoMouS** [comment]
ah....

```GO
func (e *UtlsPreSharedKeyExtension) Write(b []byte) (int, error) {
	return len(b), nil // ignore the data
}
```

**Comment by VeNoMouS** [comment]
Noticed something odd happening with `FakePreSharedKeyExtension` its calling the wrong extension to `Read()` , due to [this](https://github.com/refraction-networking/utls/blob/master/u_session_controller.go#L58)

**Comment by gaukas** [comment]
Interesting observation. I don't believe we are ready to parse raw byte ClientHello into PSK yet. On the other hand it is theoretically not possible to resume the connection with just the PSK ticket and binder from raw bytes. 

That said, it might worth debugging and fixing to make at least FakePreSharedKeyExtension work with raw bytes. But note that in the end, unexpected things would happen, such as server rejecting you for submitting a valid ticket with an incorrect binder, etc. 

Tagging @3andne for visibility.

**Comment by gaukas** [comment]
To clarify on the intended behaviors: 
- If `RealPSKResumption` is set to true: parsing from raw bytes will discard the ticket and binders from the raw bytes, but use the available ones from `ClientSessionCache` instead. 
- If `RealPSKResumption` is false: parsing from raw bytes with legitimate PSK tickets and binders IS GUARANTEED TO FAIL, given that:
    - the server will check the ticket and find it is legitimate, and proceed with verifying the binder. If we are sending binders from the original raw bytes (that's the intended behavior), the binder will not match the expected value which is calculated from all previous bytes in ClientHello. 
    - If we were to re-calculated binders, it will be a different challenge for us to find the shared secret for that specific ticket.

**Comment by gaukas** [comment]
Given all the complexities, I would encourage avoiding reusing raw bytes with PSK, either way it will not work as you expect, either we need to use a different PSK ticket/binder, or the connection will fail outright.

**Comment by VeNoMouS** [comment]
FWIW, it use to work, prior to the change

**Comment by gaukas** [comment]
> prior to the change (when genericExtension 41 was used etc)
Yep, and in that case, you would actually expect the server to return an error. Just based on my test result, when I use a legitimate PSK Identity with its original binder, the server gives me an error (due to failing the binder check). 

Have you actually observed any other behaviors? That would be really intriguing.

And a quick patch here could be just roll back to use `GenericExtension` by removing the `Writer` implementation on PSK extensions. Currently, I do not really have a good idea for how to we handle this appropriately ... or, any suggestions?

**Comment by VeNoMouS** [comment]
Yea i started doing that last night, tho ran into an issue with unable to decrypt error , trying to work out what is going on

**Comment by gaukas** [comment]
> unable to decrypt error

I don't remember exactly what error did I receive when I was testing. But there are essentially two possible outcomes: 
- Server rejects your ClientHello (you get a remote error) due to incorrect Binder (Random/GREASE/KeyShare has changed) and binder is not re-calculated
- Server didn't catch that issue and accept your resumption, sending you an encrypted message. You don't REALLY have the selected PSK Identity (more specifically, the corresponding key) so could not decrypt it.

**Comment by VeNoMouS** [comment]
> * Server rejects your ClientHello (you get a remote error) due to incorrect Binder (Random/GREASE/KeyShare has changed) and binder is not re-calculated

This gave me hint , i was testing my custom spec and i had grease place holder, replacing with rawBytes with genericExtenstion worked [here](https://github.com/refraction-networking/utls/blob/master/u_common.go#L229-L236)

Not sure why that's in a `switch` either as its only checking one case ..

Re my custom spec, i think the issue is cause i was using GREASE place holder, let me set static values

**Comment by VeNoMouS** [comment]
@gaukas what do you think about doing something with [this](https://github.com/refraction-networking/utls/blob/master/u_common.go#L227-L246)

and replace it with 
```GO
		if ext != nil && ok { // known extension and implements TLSExtensionWriter properly
			switch extension {
			case extensionPreSharedKey:
				// PSK extension, need to see if we do real or fake PSK
				if realPSK {
					extWriter = &UtlsPreSharedKeyExtension{}
				} else {
					if len(extData) == 0 {
						extWriter = &FakePreSharedKeyExtension{}
					} else {
						extWriter = &GenericExtension{Id: 41}
					}
					
				}
			case extensionSupportedVersions:
				chs.TLSVersMin = 0
				chs.TLSVersMax = 0
			}
			if _, err := extWriter.Write(extData); err != nil {
				return err
			}
			chs.Extensions = append(chs.Extensions, extWriter)
```
And adding a simple write to the GenericExtension in the tls_extensions
```GO
func (e *GenericExtension) Write(b []byte) (int, error) {
	e.Data = make([]byte, len(b))
	n := copy(e.Data, b)
	return n, nil
}
```

So if the `realPSK`  is `false` (default) it uses `FakePreSharedKeyExtension` and if the PSK is populated in the extension data it uses the genericExtension 41,  `ReadTLSExtensions`  is only called from `FromRaw`

**Comment by gaukas** [comment]
`FakePreSharedKeyExtension` is actually just a `GenericExtension` but with PSK's data fields (identity and binders) explicitly defined. So entirely removing the existence of `FakePreSharedKeyExtension` or fixing the behavior when `FakePreSharedKeyExtension` would suffice. There's no reason to keep them both.

**Comment by VeNoMouS** [comment]
Ok, i'll dive deeper into `FakePreSharedKeyExtension` and see if i can fix what ever is broken with it .. 🤞

**Comment by VeNoMouS** [comment]
Just an update on this, (sorry been busy), I can see something is happening when `FakePreSharedKeyExtension` does a `Read` , I can confirm `Write` does create the `Identities` and `Binders` , but when `Read` is executed they are gone for some reason, so I'm trying to work out what is causing that to occur

**Comment by gaukas** [comment]
Thanks for your detailed report and effort in investigation @VeNoMouS!

@3andne I would greatly appreciate if you would love to share some of your insights on this issue.

**Comment by VeNoMouS** [comment]
What if we did something like the following for [that line](https://github.com/refraction-networking/utls/blob/master/u_session_controller.go#L276) 

```GO
if s.pskExtension.Len() != 0 || s.uconnRef.Extensions[i].Len() == 0 {
	s.uconnRef.Extensions[i] = s.pskExtension
}
```

**Comment by gaukas** [comment]
It feels like that most likely you do not want to explicitly provide a PSK extension in case you are reading from raw bytes. So I would expect it to hit Line 273 instead. 

https://github.com/refraction-networking/utls/blob/df6e4c827aa5895583d53e9ccc5139077af27786/u_session_controller.go#L271-L277

**Comment by VeNoMouS** [comment]
How do you feel about adding 

```GO
case *FakePreSharedKeyExtension:
			uconn.sessionController.overridePskExt(ext)
```
to here?

https://github.com/refraction-networking/utls/blob/df6e4c827aa5895583d53e9ccc5139077af27786/u_parrots.go#L2486

**Comment by gaukas** [comment]
I'm not sure if that's the correct usage of overridePskExt()... I might need to looks into this a bit.

**Comment by VeNoMouS** [comment]
> ```go
> Identities
> ```

other option is simply...

```GO
if s.pskExtension == nil || ext.Len() != 0 {
```

https://github.com/refraction-networking/utls/blob/df6e4c827aa5895583d53e9ccc5139077af27786/u_session_controller.go#L271

**Comment by VeNoMouS** [comment]
> Why would s.pskExtension be set in this case? (Or, why do we need the or) Where is it set and what is it set to?

`syncSessionExts` gets called from `ApplyPreset` and when it creastes the `sessionController`, `newSessionController` is called which creates an empty `pskExtension`

https://github.com/refraction-networking/utls/blob/df6e4c827aa5895583d53e9ccc5139077af27786/u_session_controller.go#L54-L64

**Comment by gaukas** [comment]
> i tested that and it seems to work

Have you also tested the psk examples to make sure they all still work? 

Let's check this with 3andne first, to make sure we don't miss any part.

**Comment by VeNoMouS** [comment]
Yea lets wait for @3andne because I can envision some issues with setting it to `nil`... `overridePskExt` might be the better route...

lets wait and see

**Comment by VeNoMouS** [comment]
IMHO 

`sessionTicketExt` and `pskExtension` should both be `nil` in`newSessionController`, as there is heaps of sanity checks looking for `nil` that have safe guards in place for it

**Comment by 3andne** [comment]
@VeNoMouS Just noticed this conversation. I need some time to catch up.

**Comment by 3andne** [comment]
Hey @VeNoMouS , can you provide a minimal code snippet that can reproduce the behavior. I need your help on the context. Thanks!

**Comment by VeNoMouS** [comment]
just use the raw bytes in [the first comment](https://github.com/refraction-networking/utls/issues/248#issue-1920036550)

and use `FingerprintClientHello()` with said raw bytes to make spec and a GET to `https://tls.peet.ws/api/all` and make sure `pre_shared_key  (41)` is present in the extensions

**Comment by 3andne** [comment]
There appears to be a bug/typo, which I'll clarify. In short, the bug is in newSessionController, where we should set these to nil:
https://github.com/refraction-networking/utls/blob/df6e4c827aa5895583d53e9ccc5139077af27786/u_session_controller.go#L57-L58

-----

The `SessionController` was designed to manage all session-related operations. Initially, it had ownership over extensions. 

But this posed a challenge. The ClientHelloSpec might have a different set of PSK/Session extensions. For clarity, the original design had the `SessionController` take charge of the extensions, overwriting those from the spec. This leads to the design that `newSessionController` produces a non-nil session and a psk extension. A downside of this approach was that it altered the signature of a public method, and we didn't have a clear vision for v2.0 yet.

To circumvent this, I pivoted to a strategy where the Spec owns the extensions, ensuring the method signature remains unchanged. However, users should be able to override psk/session extensions before invoking `ApplyPreset`. These overriding extensions should exclusively reside in the `SessionController`. In such cases, the `SessionController` have ownership over the extensions.

This necessitated the creation of the `syncSessionExts` method to discern which extension takes precedence. The guiding principle is straightforward:

1. If both the user and the spec offer an extension, prioritize the user's.
2. If the spec lacks an extension and the user attempts to provide one, it's deemed an error.
3. In the absence of a user-provided extension, revert to the spec's version, if available.

Yet, during this overhaul, I overlooked the `newSessionController` method. As illustrated in the comments, deep in my mind I believe that the extension would default to nil unless overridden by the user:
https://github.com/refraction-networking/utls/blob/df6e4c827aa5895583d53e9ccc5139077af27786/u_session_controller.go#L271-L273

**Comment by VeNoMouS** [comment]
Thanks for looking at this lengthy debug ticket @3andne 😄 , are you ok if do a PR for `newSessionController `   and have

https://github.com/refraction-networking/utls/blob/df6e4c827aa5895583d53e9ccc5139077af27786/u_session_controller.go#L57-L58

Defaulting to `nil`? or do you want to do that?

**Comment by 3andne** [comment]
@VeNoMouS No problem! Thanks for your efforts!

**Comment by VeNoMouS** [comment]
Sorry about the delay in getting a PR sorted... life and all that :smile:
