### ISSUE TITLE
PSK resumption and ClientHelloRetry

### ISSUE THREAD

**Issue by let4be** [refraction-networking/utls#250]
`error: uTLS does not support reprocessing of PSK key triggered by HelloRetryRequest`
getting this error during handshake with https://httpbin.dev/anything

**Comment by gaukas** [comment]
It is a known issue simply because we didn't try to implement it given the amount of work needed. 

I don't believe there's any technical gap between uTLS and PSK by HRR, but it might still require some efforts in actually implementing and debugging. 

Until someone wants to open a PR to address this, you may either want to do something to prevent the server sending you HRR records (presumably by using a ClientHelloSpec with the server-preferred keyshare or something), or simply disable the PSK (use a fake PSK extension if you are parroting PSK?).
