### ISSUE TITLE
B uTLS does not support 0xFB1A as max version,add ja3 tls error,roundTripper error

### ISSUE THREAD

**Issue by 760644586** [refraction-networking/utls#282]
772,4865-4866-4867,43-10-51-13-0-16-45-42-41,29-23,
![image](https://github.com/refraction-networking/utls/assets/41118619/4ce88154-6433-4ea8-a80d-5539a13da020)

**Comment by gaukas** [comment]
`0xFB1A` is a custom version to the best of my knowledge. Please note uTLS has no intention of supporting any of the non-standards, since they are often not really bringing in any value. The minimum req is to at least have an IETF draft and demonstrate some degree of significance and/or be valuable to a certain use case. 

On the other hand, it should be very easy to maintain a fork of uTLS and add the support of any custom version, as long as you know it talks TLS 1.3 (for example) underneath. However, it is not something uTLS will officially endorse or support. An easy reasoning is that, if we support 0xFB1A, do we also support 0x7F17, 0xFB17, 0x7F1A, 0x7F1C? 

But, with that said, I am still open to any potential discussion or debates on the significance of a certain TLS version that is nothing new and not used by popular implementations.

**Comment by gaukas** [comment]
Duplicates #191?

**Comment by gaukas** [comment]
See https://github.com/refraction-networking/utls/issues/191#issuecomment-1605736481

**Comment by novitae** [comment]
0xFB1A is facebook's custom tls https://github.com/facebookincubator/fizz/blob/6182dd9102947ec15dcc56fabd9094294b2aeb21/fizz/record/Types.h#L23-L33

**Comment by gaukas** [comment]
Thanks for linking the source @novitae. 

Are there anything new introduced by Facebook in all these add-on versions? I still don't get what is the importance of this custom version and/or why so many people wants a parrot for it. In other words, who uses this custom version and why?

**Comment by novitae** [comment]
> Are there anything new introduced by Facebook in all these add-on versions? I still don't get what is the importance of this custom version and/or why so many people wants a parrot for it. In other words, who uses this custom version and why?

I don't really know, I think it's mostly some details. You can read more about it here: https://engineering.fb.com/2018/08/06/security/fizz/

But I highly suspect them to use it while it work almost the same as default tls13 in order to customize their fingerprints and make it harder to replicate ...

**Comment by gaukas** [comment]
Thanks. Yeah in that case I am not opposing the idea of having a parrot for it in uTLS if this is a well-known one that is really used somewhere in the world in production, will welcome any community contribution.
