### ISSUE TITLE
Failure to reading SNI from ClientHelloSepc

### ISSUE THREAD

**Issue by mrproliu** [refraction-networking/utls#319]
Hi, I'm trying to use `utls.ClientHelloSpec{}.FromRaw(bytes, true, true)` to parsing an existing client hello bytes message, and get the SNI name from the extension. 
But when I finished parsing, the SNI name extension still could not get, so [I found the codes](https://github.com/refraction-networking/utls/blob/master/u_tls_extensions.go#L165-L196), that's we were just parsing the SNI name(this is successes), but not assigned to the extension(`SNIExtension.ServerName`). Is it a kind of bug? Or what do I miss?

Thanks!

**Comment by fedosgad** [comment]
Hello!
Disclaimer: I use utls, but I am not an author/maintainer and everything below is my personal experience.

AFAIU `ClientHelloSpec` is a fingerprint "template" which can be applied to a TLS connection to any server, not just a single one (which is implied in the case of fixed SNI). Thus SNI is not preserved in `ClientHelloSpec` and must be set by a separate call of `UConn.SetSNI()` after spec has been applied (see https://github.com/refraction-networking/utls/blob/master/examples/old/examples.go) or passed in client config as usual.
So I think this is not a bug (otherwise connection to `google.com` would have a SNI of `github.com` and obviously will fail).

See also comments for [SNIExtension.Write](https://pkg.go.dev/github.com/refraction-networking/utls#SNIExtension.Write) (`SNI should not be fingerprinted and is user controlled.`) and [UClient](https://pkg.go.dev/github.com/refraction-networking/utls#UClient) (`make sure to eventually specify ServerName`).

**Comment by mrproliu** [comment]
Hi, @fedosgad . Thanks for your reply!

I got it. So, in my scenarios, do you have any suggestions for getting the SNI name from parsing the Client Hello Bytes Message?

**Comment by fedosgad** [comment]
I don't know about libraries specifically for parsing ClientHello (there possible are some in the wild).
You can do parsing yourself (if the only thing you need is SNI that shouldn't be hard) - https://pkg.go.dev/golang.org/x/crypto/cryptobyte may help you.
