### ISSUE TITLE
Cannot instantiate extensions due to unexported fields

### ISSUE THREAD

**Issue by rod-hynes** [refraction-networking/utls#33]
I am unable instantiate a `utls.ClientHelloSpec` containing a functional `utls.RenegotiationInfoExtension` because its `renegotiation` field is not exported.

E.g., I need to construct something like the following outside the `utls` package, and then use it with `utls.HelloCustom`.
```
utls.ClientHelloSpec{
	Extensions: []utls.TLSExtension{
		&utls.RenegotiationInfoExtension{
			renegotiation: RenegotiateOnceAsClient}
	}
}
```

`RenegotiationInfoExtension` does have an exported field, `SecureRenegotiation`, but looking at `RenegotiationInfoExtension.writeToUConn/Len/Read`, it appears that `renegotiation` must be set to something other than its zero value of `RenegotiateNever` for the extension to get added to the ClientHello and for the `HandshakeState.Hello.SecureRenegotiationSupported` flag to get set.

https://github.com/refraction-networking/utls/blob/4da67951864128358459681399dd208c49d5d001/u_tls_extensions.go#L217-L231

Incidentally, this code in `RenegotiationInfoExtension.Read` looks odd. When `e.SecureRenegotiation` is not empty,  `secureRenegBody` points to `e.SecureRenegotiation`. And then that data is copied first starting at offset 4 and again at offset 5?

https://github.com/refraction-networking/utls/blob/4da67951864128358459681399dd208c49d5d001/u_tls_extensions.go#L241-L255

In addition, I can't instantiate a `utls.GenericExtension` as both of its fields are unexported.

https://github.com/refraction-networking/utls/blob/4da67951864128358459681399dd208c49d5d001/u_tls_extensions.go#L367-L370

**Comment by sergeyfrolov** [comment]
> code in RenegotiationInfoExtension.Read looks odd.
Renegotiation Extension is nasty both in its implementation and idea, and maybe should be disabled by default in uTLS. When I wrote first version of the renegotiation extension marshaling in uTLS, I was looking at this code from standard crypto/tls: https://github.com/golang/go/blob/release-branch.go1.11/src/crypto/tls/handshake_messages.go#L256
Note how all other extensions fill bytes 2 and 3 with the length of extension body, because that's where the length should go, and it usually looks something like this:
```
		z[2] = byte(extensionBody >> 8)
		z[3] = byte(extensionBody)
```
Renegotiation code, however, did THAT:
```
		z[2] = 0
		z[3] = byte(len(m.secureRenegotiation) + 1)
		z[4] = byte(len(m.secureRenegotiation))
```
I'll be honest and say that I do not completely understand wtf is going on and why things are this way. I simply confirmed that standard cases are making sense, and that my Chrome/Firefox/etc parrots do look like what they should look like, that RenegotiateOnceAsClient is a fair default for my parrots, and I called it a day.
I did the same when I updated the uTLS to TLS 1.3.

Major browsers use a single 0x00 byte as a body of this renegotiation extension, so the entire extension ends up being `ff 01 00 01 00` where `ff 01` is extension type, `00 01` is length of extension body, and `00` is the body. `00` is actually also a length of the inner body, so the real body payload starts at offset 5.
That's where the `[]byte{0}` body case comes from: we want the right default. However, if user specified their own body, they presumably know what they're doing, so I tried to copy the body they specified into the extension.
You are extremely welcome to clean those few lines up with what makes more sense to you and send a PR. It seems like you also have gotten a good sense of what things should be happening.

The fields not being exported is a bug. Would you be willing to send a PR that exports all of them? Otherwise, I will probably find some time in the next few weeks to do that myself.

**Comment by sergeyfrolov** [comment]
Alright, the way I did things actually does make sense. Shoulda left a comment to not have to read the extension rfc again:
https://tools.ietf.org/html/rfc5746
```
   This document defines a new TLS extension, "renegotiation_info" (with
   extension type 0xff01), which contains a cryptographic binding to the
   enclosing TLS connection (if any) for which the renegotiation is
   being performed.  The "extension data" field of this extension
   contains a "RenegotiationInfo" structure:

      struct {
          opaque renegotiated_connection<0..255>;
      } RenegotiationInfo;

   The contents of this extension are specified as follows.

   o  If this is the initial handshake for a connection, then the
      "renegotiated_connection" field is of zero length in both the
      ClientHello and the ServerHello.  Thus, the entire encoding of the
      extension is ff 01 00 01 00.  The first two octets represent the
      extension type, the third and fourth octets the length of the
      extension itself, and the final octet the zero length byte for the
      "renegotiated_connection" field.

   o  For ClientHellos that are renegotiating, this field contains the
      "client_verify_data" specified in Section 3.1.

   o  For ServerHellos that are renegotiating, this field contains the
      concatenation of client_verify_data and server_verify_data.  For
      current versions of TLS, this will be a 24-byte value (for SSLv3,
      it will be a 72-byte value).
```
