### ISSUE TITLE
Replace Yawning/chacha20 PRNG

### ISSUE THREAD

**Issue by renzhexigua** [refraction-networking/utls#36]
In the latest commit: https://github.com/Yawning/chacha20/commit/644b09ac4e6e3ed1c52aa43dad519087d8bca406, the author did some non backward-compatible changes. One of them is:

> `NewCipher` -> `New`

We should fix this piece here:

https://github.com/refraction-networking/utls/blob/7c97cdb47655017af7126d6c5cd23ace4469d7aa/u_prng.go#L119-L120

**Comment by Yawning** [comment]
So, as a fair warning, the commit in question also changes the license to something that's probably not suitable for this project as well.

That said, in the spirit of "sorry I broke your package":

 * Using go modules (since utls requires a new-ish version of the toolchain anyway) will prevent dependency changes from breaking code in the future in this manner (till the dependencies are updated), and would also let you pin the chacha20 import to the previous commit.

 * https://godoc.org/github.com/aead/chacha20 is probably a suitable replacement, if people want to stick to ChaCha20, though skimming the code it does panic on counter overflow.  Personally I opted to save an import and just use SHAKE.

**Comment by renzhexigua** [comment]
A useful circumvention way.

**Comment by sergeyfrolov** [comment]
So, uTLS package is broken.

I do not think pinning chacha20 import to a previous commit is a good idea going forward. We'll have to find a replacement.

>  the commit in question also changes the license to something that's probably not suitable for this project as well

@rod-hynes does this affect you in any way? Do you happen to know any good replacement PRNG packages?

Seems like SHAKE (https://godoc.org/golang.org/x/crypto/sha3) could indeed be a good replacement.

**Comment by rod-hynes** [comment]
> @rod-hynes does this affect you in any way?

We don't have any immediate issues since we vendored an earlier version of this: https://github.com/Psiphon-Labs/psiphon-tunnel-core/tree/master/vendor/github.com/Yawning/chacha20.

SHAKE seems fine and should simplify the code in https://github.com/refraction-networking/utls/blob/master/u_prng.go since there's no stream limit, so no need to rekey. I think SHAKE is somewhat slower than chacha20 (https://bench.cr.yp.to), but that's not relevant here, with few bytes generated.

Changing the cipher means a one-time change in randomized fingerprints generated by persisted seeds. I think we're ok with that. So as long as the API remains the same -- can the same seed size be used? Something like:

```
p.randomStream := NewShake256()
_, err := p.randomStream.Write(seed[:])
```

**Comment by Yawning** [comment]
> can the same seed size be used?

Yes.  An arbitrary amount of data can be absorbed.
