### ISSUE TITLE
Fallback cipher list

### ISSUE THREAD

**Issue by blakebyrnes** [refraction-networking/utls#91]
Chrome 88 will send a fallback cipher list that includes TLS_RSA_WITH_3DES_EDE_CBC_SHA on top of it's regular list if a server replies with a server rejection to the client hello. (see esaj.tjsp.jus.br for an example site).

Is there anything built-in at the moment to do a fallback cipher list?

**Comment by gaukas** [comment]
I know this issue is pretty old now, but actually it is a good question to ask, as a part of a larger-scale fingerprint-ability. 

- Is the fallback behavior on the same TCP connection, or a different one? 
- Is the fallback behavior deterministic/predictable? (fallback of fallback, fallback of fallback of fallback...)
- How, and to what extend, do we want or need to capture the behavior of a certain TLS client, to be (mostly) fingerprint-proof.
